### ISSUE TITLE
Invitation Badge release Process

### ISSUE THREAD

**Issue by TatsuyaIshibe** [henkaku-center/badge#32]
# Variables
- badge address:  `0x2C3530B4642ff8fCEb6ab5Fc740381a358968aF1`
- gnosis address: `matic:0x2B3cFCe8a10Bd49553CE300CDA910bAc3b4ABdF5`
  - method: `createBadge`
  - tuple: `[ true, true, 1000000000000000000000, 10, 'https://bafkreifemv7ioh4gih4kglfsctjwoyk367fujeppagyvlgvsefraky2xui.ipfs.dweb.link/?filename=invitation-ticket.json', 3] `
  - badge struct: https://github.com/henkaku-center/badge/blob/main/contracts/HenkakuBadge.sol

# Process
1. [Go gnosis](https://gnosis-safe.io/app/matic:0xEd7e3f5f9A1f564cb4A72c1d05B6DC507B13f43d/transactions/history) with owner address
3. enter badge address and execute createBadge with tuple
4. check the [omise](https://omise.henkaku.org/ja/badges/).

**Comment by TatsuyaIshibe** [comment]
@SamuraiT Is this correct for tuple?

**Comment by SamuraiT** [comment]
mostly it is correct but in process we should have + we'd better to use web3 storage cuz it seems much better than pinata
1. create pr with metadata like this https://github.com/henkaku-center/badge/pull/33#pullrequestreview-1046616976
2. gnosis
